### ISSUE TITLE
Error on cardset download

### ISSUE THREAD

**Issue by starplatinum92** [bstaple1/MTGA_Draft_17Lands#10]
Hi, i'd just download Magic Draft Tool v2.91 (exe for Windows) but when i go to search setdata to download it give me an error: "Download Failed: not enough values to unpack (expexted 3, got 2)". it gave me this error no matter what i put in search filters.
I have attached the debug log in case you wanna look it up.
Thanks for your patience and sorry for my bad english.
[debug.log](https://github.com/bstaple1/MTGA_Draft_17Lands/files/9150682/debug.log)

**Comment by starplatinum92** [comment]
Hi bstaple1,

I wanna thank you for your fast reply.
Yes, my folders name are located in Italian and i had enabled the detailed logs from the game.
Now that i look better there are something strange with the root on my drive. I will invastigate and 
reply as soon as possible.

**Comment by bstaple1** [comment]
If you're able to identify the location of the Player.log file, then you can manually enter the location path in the windows command window.

![image](https://user-images.githubusercontent.com/96687942/180044113-b54d5772-6b0f-425e-b30b-743483442e1b.png)

**Comment by starplatinum92** [comment]
After a clean install of Windows all just went fine. I had some trouble with User name from the previous install of Windows, that cause me some path root mismatching. Very great job mate. App very handly and usefull. Kudos to you!!
