### ISSUE TITLE
Attempting to add my 17lands tier list

### ISSUE THREAD

**Issue by classic80srock** [bstaple1/MTGA_Draft_17Lands#12]
hello, great project, I've been trying to add my 17lands tier list but it isn't showing up in the Decks drop down list.  I downloaded my tier list according to the directions, added it to the MtgaDraftTool windows directory, and added the label and set name.  Any clarification on the file name the app is looking for or file type (i left it as a json file and also added a txt file just in case).  thanks in advance.

**Comment by bstaple1** [comment]
Hi classic80srock, I'm happy to hear that you like the project. Could you please attach your tier list so that I can try and reproduce the issue? Thanks.

**Comment by classic80srock** [comment]
[Tier_1658678578293.txt](https://github.com/bstaple1/MTGA_Draft_17Lands/files/9176125/Tier_1658678578293.txt)
I am also using the windows App, not python.

**Comment by bstaple1** [comment]
I was able to reproduce the issue. With a few tweaks to the application and the tier list extension, I'm now able to see your tier list listed in the drop-down. I added a Tier folder to hold the tier list files. 
I placed my changes in the branch DEV_0295. If it isn't too much trouble, could you download the DEV_0295 branch [here](https://github.com/bstaple1/MTGA_Draft_17Lands/archive/refs/heads/DEV_0295.zip), run through the python steps, and confirm that the change is working? If it's working, then I will merge the changes into a release later this week.

**Comment by bstaple1** [comment]
I made some additional changes to support multiple tier lists per set (previously unsupported). The application will now list the tier list with a sequential number next to the word Tier (i.e., Tier0, Tier1, etc.). 

To make it easier to confirm that the feature is working, I pushed a draft log to the DEV_0295 branch (DraftLog_HBG_BotDraft_1657658456.log in the /Logs folder). You can open this draft log within the application by going to File->Open. Please close the issue once you confirm that the tier list is showing up. 

![image](https://user-images.githubusercontent.com/96687942/180667153-cce04293-1db8-413d-8184-623bfa8861db.png)
![image](https://user-images.githubusercontent.com/96687942/180667154-080c4ae8-01fc-41a9-a112-22a0317fb5c7.png)
![image](https://user-images.githubusercontent.com/96687942/180667157-060cb572-07ab-47d5-854b-fe1e1475694a.png)

**Comment by classic80srock** [comment]
thank you for your hard work on this, I really don't know much about Python.  I will have to trust that your next build will work just fine based on the images.
