### ISSUE TITLE
Parsing not working

### ISSUE THREAD

**Issue by spam8117** [bstaple1/MTGA_Draft_17Lands#13]
Hi, unfortunately I can't get it to work at all.
My MTGA installation is standard, and my MtgaDraftTool is in C:

Detailed logs are active, but there is no log generation within C:\MtgaDraftTool\Logs.
I didn't have Magic Draft running when I started the draft. Now it seems to detect something as I tried starting one Historic battle.
But going back to my draft (pack 2, pick 1) nothing happens. The set is downloaded and ready.

I attached the debug.log for you to look at. Do I need anything else to make it work? I just installed the setup.exe and did no further steps so far. Cheers!

[debug.log](https://github.com/bstaple1/MTGA_Draft_17Lands/files/9277455/debug.log)

**Comment by bstaple1** [comment]
Thanks for letting  me know. 

From what I'm seeing, the application is only detecting the one event. Could you share the Player.log file from C:\Users\skillR\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log? If you're not comfortable sharing it publicly, then you could reach out to me on Discord at Wumpus#3068.

**Comment by spam8117** [comment]
I added you on Discord (my name there is Tommyツ).

**Comment by bstaple1** [comment]
We checked the Arena log and discovered an issue where the tool is unable to track the draft if Arena is reopened mid-draft. We've confirmed that this is at least an issue for Quick Drafts. I will confirm if this is also an issue for Premier Drafts.

I will make a fix for this issue in the next release.

**Comment by bstaple1** [comment]
This issue has been addressed in [version 3.00](https://github.com/bstaple1/MTGA_Draft_17Lands/releases/tag/MTGA_Draft_Tool_V0301).
