### ISSUE TITLE
Sorting & Card Colors

### ISSUE THREAD

**Issue by Ganadai** [bstaple1/MTGA_Draft_17Lands#16]
I've noticed that if I sort by GIHWR on P1P1 that it does not save the choice, and I have to click GIHWR on every pick.  A default sort method option would be nice.

Why do all cards with a kicker cost display as gold cards?  Really throws me off when I'm drafting.

**Comment by bstaple1** [comment]
Hi Ganadai,

The application automatically sorts the tables by the last column whenever an update is detected. You can set the last column to GIHWR if you want the application to sort by that field for each pick.

The application assigns row colors based on the card's color identity. I agree that this is a problem for DMU and I'm currently working on some modifications to address it.

Thanks for the feedback.

**Comment by Ganadai** [comment]
Thanks for the info!  I figured out I can edit the card colors in the .json data files for now, but since all the card set numbers are ordered by color, it shouldn't be too difficult to program something like 
If set = DMU & set number >=2 & set number <= 39 Then color = White

That explains why you had GIHWR in the last column!  Tool tips in the settings would be great.

**Comment by bstaple1** [comment]
Enhancement made to version 3.03
