### ISSUE TITLE
Tool doesn't work

### ISSUE THREAD

**Issue by masu1208** [bstaple1/MTGA_Draft_17Lands#17]
It never works in any type of game and I get a DraftStartSearch Error: 'cp932' codec can't decode byte 0x87 in position 3093: illegal multibyte sequence error in debug.log I have a problem with this. I believe the problem is probably that player.log is saved as cp932, but python uses UTF-8.

**Comment by bstaple1** [comment]
Hi masu1208,

If I'm understanding the error correctly, it appears that the application is trying to open the file with a cp932 codec. The application doesn't explicitly set the codec so it's using a codec assigned by your operating system. You can check the assigned codec by following the steps in the image below.

![image](https://user-images.githubusercontent.com/96687942/189532231-9f492bfb-9f40-4544-a7e6-e06edc45482d.png)

The code in branch DEV_0303 sets the code to "utf-8", which appears to be the right code for the player.log file. Could you please run the python code in branch DEV_0303 to confirm that this is no longer an issue?

Thanks for bringing this to my attention.

**Comment by masu1208** [comment]
I have confirmed that it works in Premier Draft, Quick Draft and Shield.

**Comment by bstaple1** [comment]
Issue resolved in version 3.03
