### ISSUE TITLE
Scryfall data unavailable

### ISSUE THREAD

**Issue by Girtti** [bstaple1/MTGA_Draft_17Lands#18]
Hi there! Great work and I highly appreciate it!
Unfortunately, when I try to upload DMU set, I cannot reach Scryfall data.
![image](https://user-images.githubusercontent.com/97792795/190319841-cbfa6afa-eddf-4b9b-877e-8d4f4df4b630.png)
![image](https://user-images.githubusercontent.com/97792795/190319888-6e0a0b35-32e0-4685-bc61-86633b7ca8b1.png)

Is this because of embargo? Is it just me?
Also, is there anything I can do with that?

Win build 3.03

**Comment by bstaple1** [comment]
Could you click on the _Default Settings_ button in the settings window and re-try the download?

Also, could you attach your debug.log file from the _Debug_ folder? 

Thanks.

**Comment by Girtti** [comment]
Thank you for the quick response!
<09/15/2022 12:20:55>,https://www.17lands.com/card_ratings/data?expansion=DBL&format=QuickDraft&start_date=2019-1-1&end_date=2022-09-15&colors=BG
<09/15/2022 12:20:55>,retrieve_17lands_data Error: HTTP Error 503: Service Temporarily Unavailable


[debug.log](https://github.com/bstaple1/MTGA_Draft_17Lands/files/9573896/debug.log)

Also, tons of errors
<09/15/2022 11:38:24>,__arena_log_check Error: [WinError 3]

And some
<09/15/2022 11:35:37>,Couldn't Collect Local Card Data
<09/15/2022 11:37:08>,_process_scryfall_data Error: 'image_uris'

**Comment by bstaple1** [comment]
Thanks for the log.

The tool searches the C,D,E,F drives for the Player.log file. 
**Example:** C:\Users\bstaple1\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log

What drive letter are you using?

**Comment by Girtti** [comment]
C, D and E

**Comment by bstaple1** [comment]
Can you identify the location of the Player.log file?

Is it in any of the _<Drives C,D, or E>:\Users\<Username>\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log_ folders?

**Comment by Girtti** [comment]
C:\Users\N******v\AppData\LocalLow\Wizards Of The Coast\MTGA

It tries to search "N.***" user, while logs and everything is on "N ....V"

**Comment by Girtti** [comment]
Works superb! 2 more questions: 1) is there a way to manually upload json into the Magic Draft? Like if I have json and wanna use it manually? 2) I uploaded 7 more sets for Quick and Premier draft today. Should I reupload them anyhow now? Or it will work fine?

**Comment by bstaple1** [comment]
1. I'm going to need more context to answer this question
2. That shouldn't be necessary. The sets that you've already downloaded should work.
3. No, there's no auto update for the set data. 17Lands only updates their data once a day sometime between 01:30 and 03:00 UTC. 

**Note**: 17Lands will time out a download request, producing the _HTTP Error 503: Service Temporarily Unavailable_ result, if you try to download too many sets within a short period of time. Try to only download at most 2 sets in a 15 minute period

**Comment by Girtti** [comment]
Got it!
