### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by Ganadai** [bstaple1/MTGA_Draft_17Lands#19]
All the sort options currently default to descending order.  

Could ASLA and ATA default to ascending order instead?

Earlier I made a comment that it doesn't work in the sealed event.  It appears it only works if you're running the program when you purchase an event.  If I later open the deck editor for a draft / sealed event, the program will not display taken cards or suggested deck.  This is why I originally thought it didn't work with sealed events.  I would assume it's possible to do because other similar programs can. 

Is there any way for people to donate to this project?

**Comment by bstaple1** [comment]
Arena clears the player.log file whenever the program is restarted, so data from earlier in the draft (e.g., taken cards) can't be read from that file.

The solution is to to keep the draft log setting enabled while you draft or play sealed. This feature will write all of your draft data to a file in the ./Logs folder that you can then open later (File->Open) to see your draft/sealed data.

Note: If you open a log file, then the application will no longer read from the player.log file unless you select File->Open with the player.log or you restart the tool.

![image](https://user-images.githubusercontent.com/96687942/190853141-a4fc1508-adc7-40c9-bc41-1d6512c0c16b.png)
![image](https://user-images.githubusercontent.com/96687942/190853220-ee3b2f92-b849-4725-8877-7a81b33406a6.png)

No, there's currently no way for people to donate to this project.
