### ISSUE TITLE
CalculateColorAffinity fails if 17lands data is incomplete

### ISSUE THREAD

**Issue by maqifrnswa** [bstaple1/MTGA_Draft_17Lands#2]
similar to #1 , if a card doesn't have data for a certain color combination, calculatecoloraffinity won't finish calculating the remaining cards:

swapping "try" and "for" here:
https://github.com/bstaple1/MTGA_Draft_17Lands/blob/dc97857a2279e6908da9b216a5bfae1546a9b4be/card_logic.py#L241

will fix it!
thanks!

**Comment by bstaple1** [comment]
Thanks for bringing this to my attention. I will make the change
