### ISSUE TITLE
Scryfall page for DMU returns cards without any arena_id which causes failure to download set data

### ISSUE THREAD

**Issue by bikeboy99** [bstaple1/MTGA_Draft_17Lands#21]
One of the URLs returned by the Scryfall API for DMU (`'next_page'`) is this page:

[`https://api.scryfall.com/cards/search?format=json&include_extras=false&include_multilingual=false&include_variations=false&order=set&page=3&q=e%3Admu&unique=prints`](https://api.scryfall.com/cards/search?format=json&include_extras=false&include_multilingual=false&include_variations=false&order=set&page=3&q=e%3Admu&unique=prints)

Please note this is not for DMU Alchemy - this is for DMU.

Because it has no arena_id for any cards, [this continue statement](https://github.com/bstaple1/MTGA_Draft_17Lands/blob/main/file_extractor.py#L987-L988) is triggered for each card.[ `result `is never set to true](https://github.com/bstaple1/MTGA_Draft_17Lands/blob/main/file_extractor.py#L1013) and the application thinks that the overall download failed.

**Comment by bikeboy99** [comment]
I was able to get it to work by modifying the code to track if there ever was a result for any page. I suppose this could lead to partial results in some cases. Just a temporary workaround.

**Comment by bikeboy99** [comment]
Apologies - didn't mean to close the issue I don't use github often.

**Comment by bstaple1** [comment]
Hi bikeboy99,

Thanks for bringing this to my attention. I haven't had time to play Magic recently, so I appreciate it when people report issues with the tool.

I will investigate this when I get a chance.

**Comment by bstaple1** [comment]
@bikeboy99 [version 3.03](https://github.com/bstaple1/MTGA_Draft_17Lands/releases/tag/MTGA_Draft_Tool_V0304) has a fix for this issue.

Note: The auto-update feature in 3.03 is broken, so you will need to re-download the application from the release page.

Thanks for the help.
