### ISSUE TITLE
Retro Artifacts not appearing in tool

### ISSUE THREAD

**Issue by kaiyoshino** [bstaple1/MTGA_Draft_17Lands#24]
Retro Artifacts don't appear in the draft tool. Below is a screenshot of Taken Cards where you can see they are not showing, but they also don't show during the draft. I see the Retro Artifacts on 17Lands. Is there an issue with my download of the card data maybe?
![image](https://user-images.githubusercontent.com/11436089/202311783-0f84a52c-36e4-43f2-9187-8172164cd270.png)
![image](https://user-images.githubusercontent.com/11436089/202311818-d7cd148e-e053-45d7-aaef-8d0760bb4ce3.png)

**Comment by bstaple1** [comment]
I just checked the downloaded card data and I'm seeing Bone Saw and Gilded Lotus. It's possible that there's a log parsing issue.

Could you attach your _DraftLog_BRO_PremierDraft_ file from the _Logs_ folder? This file contains the Arena log entries from which this application is pulling the draft data.

Thanks.

**Comment by kaiyoshino** [comment]
[DraftLog_BRO_PremierDraft_ddf560ea-6278-4804-bc7d-4d71428c3c9d.log](https://github.com/bstaple1/MTGA_Draft_17Lands/files/10026819/DraftLog_BRO_PremierDraft_ddf560ea-6278-4804-bc7d-4d71428c3c9d.log)
Attached. Thanks.

**Comment by bstaple1** [comment]
I'm seeing the missing cards when I read your log (_File_->_Open_).

![image](https://user-images.githubusercontent.com/96687942/202331921-95779a65-a0e8-435b-8747-7a2069d7cb44.png)

If you open up the debug.log file in the Debug folder, and you search for the word _error_, do you see any entries?

Also, could you re-download the set, open the log file, and confirm that you're still not seeing those cards?

**Comment by kaiyoshino** [comment]
The issue has gone away after re-downloading the set. Thanks for your quick and attentive responses!
