### ISSUE TITLE
Tier lists not downloading correctly?

### ISSUE THREAD

**Issue by r00kier00kie** [bstaple1/MTGA_Draft_17Lands#28]
I've been having some trouble getting the Tier List feature to work. Following the instructions given, I've managed to download the .txt file, but it doesn't seem to contain the info I've input at 17lands, as the ratings section is empty:

{
    "meta": {
        "collection_date": "3/27/2023 11:57:53",
        "label": "SIR",
        "set": "SIR",
        "version": 2
    },
    "ratings": {}
}

Tier list I'm trying to import: https://www.17lands.com/tier_list/8a39f0e1bba34a4590545bdca919b464
Apologies if this has been addressed elsewhere.

**Comment by r00kier00kie** [comment]
Thanks, logging out resolved the problem for me. I'll leave it up to you if/when to mark as closed. The app has been just what I've been looking for so thanks for your work on it!

**Comment by bstaple1** [comment]
This issue was fixed in release [3.08](https://github.com/bstaple1/MTGA_Draft_17Lands/releases/tag/MTGA_Draft_Tool_V0308).
