### ISSUE TITLE
new auto color logic can possibly never find a solution

### ISSUE THREAD

**Issue by maqifrnswa** [bstaple1/MTGA_Draft_17Lands#3]
first off, great project - this is very well done!

I like the idea behind the new autocolor logic:
https://github.com/bstaple1/MTGA_Draft_17Lands/blob/dc97857a2279e6908da9b216a5bfae1546a9b4be/card_logic.py#L227
but I loaded up 3 different drafts, and all 3 wouldn't have found the right color until around pick 35 or 40.

That happens because it often leads to the following situation: after the 15th pick, the two top color combos are often within 30 pts of each other (especially if the first pack was heavy on a single color so that 2 two-color ratings are way ahead of the others, but close in value to each other). The logic then keeps on suggesting the best "all decks" pick, which is somewhat randomly distributed among all colors. Since the threshold decays linearly until the very last pick (#45), it will go deep in to the 3rd pack before switching over (since each new card might actually go to deck colors that are very far from optimal).

Suggestions:
Maybe start at 30 instead of 45 at this line?
https://github.com/bstaple1/MTGA_Draft_17Lands/blob/dc97857a2279e6908da9b216a5bfae1546a9b4be/card_logic.py#L227
this way it's guaranteed to give a solution by the start of pack 3 and would switch over if two decks are only within 15 pts after the 15th pick.

Or display the current color weights somewhere on the UI so it's clear when there are two close "contenders"? This is already output to the console when set to "auto" color.

Or the "auto" card rating after the 15th pick is the greater of the top two color decks' rating for the card until it settles on a color? (or the average rating of the top two?) This prevents it from giving cards high ratings that have no chance of actually being included in the end (because it's colors are so far off from the top two).

**Comment by bstaple1** [comment]
Thanks for the feedback. This issue is a bit tricky, but your solutions are reasonable.

**Comment by bstaple1** [comment]
I created a branch (DEV_0274) that contains the logic in your third solution. If there is not a clear leading color pair, then the tool will take the top two colors pairs and average the ratings together.
