### ISSUE TITLE
DFCs don't work and aren't rated while drafting

### ISSUE THREAD

**Issue by cyan2k** [bstaple1/MTGA_Draft_17Lands#30]
![image](https://github.com/bstaple1/MTGA_Draft_17Lands/assets/40628958/c0c7b7ce-3b9f-4844-a7b5-b132da03f308)

See screenshot.
MOM draft on newest MacBook/MacOS.

Don't know if it's a MTGA issue or an overlay issue, but fixes to it would be appreciated.
Tried to delete the contents of the com.wizards.mtga/Downloads/Raw folder but it didn't solve the issue.

**Comment by bstaple1** [comment]
I wasn't able to reproduce the malformed database issue that you're experiencing. 

The application uses Scryfall as a fallback if it's unable to collect the card data from the Arena files. There was a DFC bug in 3.08 that I fixed in version 3.09.
