### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by riQQ** [bstaple1/MTGA_Draft_17Lands#32]
As far as I can see, Linux is currently not supported. Any chance you could add Linux support?

**Comment by bstaple1** [comment]
Although I haven't personally tested it, the application should work on Linux, except for the automatic player log detection. If you know the location of the Player.log file, then you can set that location in the application by clicking File->Open.

**Comment by riQQ** [comment]
Using `requirements_mac.txt`, right?

**Comment by bstaple1** [comment]
Yes

**Comment by riQQ** [comment]
This is now documented in the updated Readme.
