### ISSUE TITLE
Pydantic version error

### ISSUE THREAD

**Issue by yuengan** [bstaple1/MTGA_Draft_17Lands#34]
`pip install -r requirement.txt` installed pydantic 2.0 and it led to following error.

```
raise PydanticUserError(
pydantic.errors.PydanticUserError: The `field` and `config` parameters are not available in Pydantic V2, please use the `info` parameter instead.

For further information visit https://errors.pydantic.dev/2.0/u/validator-field-config-info
```

Downgrading pydantic to 1.10.10 solves the problem.

**Comment by bstaple1** [comment]
I updated the requirements document so that it installs a 1.* version.

I will look into pydantic V2 when I get a chance.
