### ISSUE TITLE
pedantic version error

### ISSUE THREAD

**Issue by nottooloud** [bstaple1/MTGA_Draft_17Lands#36]
version.txt in 310 says 3.09

**Comment by bstaple1** [comment]
Are you referring to [this Pydantic version error](https://github.com/bstaple1/MTGA_Draft_17Lands/issues/34)? If so, then you need to run the `pip install -r requirements.txt` command using the requirements.txt file that's in the main branch, not the file that's tagged in the 3.10 release. You can also enter `pip install pydantic==1.*` to set the correct version of Pydantic.

**Comment by nottooloud** [comment]
Well, I was referring to it, but just wordplay on the title. 
version.txt in 310 says 3.09. Shouldn't it say 3.10?

**Comment by nottooloud** [comment]
Completely pedantic. a little Sunday humour.
