### ISSUE TITLE
no values for adventure cards

### ISSUE THREAD

**Issue by einsz** [bstaple1/MTGA_Draft_17Lands#38]
Hello,

the client does not seem to pull the ratings for any of the adventure cards from the new Wilds of Eldraine set. It justs lists them as 0.
I think they may be named differently? The MTGA draft client lists them with both names (Beluna's Gatekeeper // Entry Denied) but in 17lands it is just listed by the main card name.

**Comment by bstaple1** [comment]
Could you send me the debug.log file from the Debug folder? You can attach the file to this issue.

**Comment by einsz** [comment]
[debug.log](https://github.com/bstaple1/MTGA_Draft_17Lands/files/12597694/debug.log)

**Comment by bstaple1** [comment]
It appears that you're encountering the issue addressed in pull request #37. Additionally, I'm observing an unrelated error associated with the tooltip images and version 10.0.0 of the Pillow library. 

Switch to the main branch and rerun the `pip install -r requirements.txt` command to resolve both of these issues.

**Comment by einsz** [comment]
Ah, i used the V0310 release.
Yes, its working with the latest commits to main branch.
Thank you.
