### ISSUE TITLE
first pack does not register in draft helper

### ISSUE THREAD

**Issue by einsz** [bstaple1/MTGA_Draft_17Lands#39]
When i start a new draft it wont list any cards in the draft helper client until i do my first pick.
It worked fine before, this seems to be a new problem, maybe related to a MTGA update?

**Comment by bstaple1** [comment]
Are you participating in a premier or traditional draft? If so, then the Arena player log doesn't list pack 1, pick 1 data until after your first pick. This is a well known issue with the Arena logs that the developers haven't fixed. There's a note in the run steps that mentions this.

![image](https://github.com/bstaple1/MTGA_Draft_17Lands/assets/96687942/7eb58112-6f1b-4d7d-bff8-6a273b2b8054)


When it worked fine before, were you participating in a quick draft? This isn't an issue for quick drafts.

**Comment by einsz** [comment]
Yes, sorry. This was my first premier draft, so i didn´t notice it before.
