### ISSUE TITLE
Download Failed: Arena IDs Unavailable

### ISSUE THREAD

**Issue by Frritz** [bstaple1/MTGA_Draft_17Lands#7]
Getting an error saying Download Failed: Arena IDs Unavailable when attempting to add set data for any drafts in SNC.
All other sets seem to add with no issue.
Using version 2.83.

**Comment by bstaple1** [comment]
I have a few questions:
- Mac or PC?
- If PC, do you see "C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Downloads\Data" or  "C:\Program Files (x86)\Wizards of the Coast\MTGA\MTGA_Data\Downloads\Data" folders?
- If Mac, do you see a "Users/<User name>/Library/Application Support/com.wizards.mtga/Downloads/Data/" folder 
- Did you run this tool while Magic Arena was updating?

I will look into this issue. In the meantime, set the ID to 80152 when you download the SNC set.
![image](https://user-images.githubusercontent.com/96687942/168243581-2dade9ca-46e6-4ee1-9a64-595aea51f49d.png)

**Comment by Frritz** [comment]
- I'm on PC, using 64 bit Windows 10
- My MTGA is installed to a different drive, but I do see the data folder
- Arena wasn't running while I tried adding the set data before, but I just opened it to make sure no updates were pending and got the same result

Thank you, changing the ID does seem to have let it download without issue

**Comment by bstaple1** [comment]
The card IDs are now available online, so it's no longer necessary to enter the ID when downloading the SNC set. Keep the ID at the default 0.

I'm working on a new build (DEV_0284) that will be able to read files for multiple drives. This will be available before the next set is released.
